<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirstBoard\FirstBoard.csproj" />
    <ProjectReference Include="..\Player\Player.csproj" />
    <ProjectReference Include="..\Player.Llm\Player.Llm.csproj" />
  </ItemGroup>

</Project>
