<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DurableGraphGenerateDefinitions>true</DurableGraphGenerateDefinitions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Atelia.DurableGraph" Version="$(DurableGraphPackageVersion)" />
    <ProjectReference Include="..\Kernel\Kernel.csproj" />
  </ItemGroup>

</Project>
